### ISSUE TITLE
How to enable cppcheck addons?

### ISSUE THREAD

**Issue by ptskyin** [QiuminGe/cpp-check-lint#28]
I'm trying to use the MISRA addon in cppcheck. The corresponding cppcheck command is:
` cppcheck --addon=misra .\test.c` 
How can I enable it in cpp-check-lint?

**Comment by QiuminGe** [comment]
try v1.4.3
CppCheck:--addon=["misra"]

support
cppcheck --addon=cert --addon=y2038 src/test.c

unsupport
cppcheck --dump --quiet src/test.c
python cert.py src/test.c.dump
python misra.py --rule-texts=~/misra_rules.txt src/test.c.dump

**Comment by ptskyin** [comment]
Thanks, QiuminGe! The MISRA warning now shows.
One more question:
Possible to support the following method to use _**misra_rules.txt**_? I tried this way, but seems not working.
![image](https://user-images.githubusercontent.com/8570671/119462861-c3468700-bd73-11eb-8a80-5880c4632726.png)

**Comment by QiuminGe** [comment]
I updated read me in v1.4.4
Can it solve your problem？
![image](https://user-images.githubusercontent.com/79127100/119635014-cb013c80-be02-11eb-886c-b207365f801d.png)

**Comment by QiuminGe** [comment]
"args": [
        "--rule-texts=misra.txt"
    ]
Do you know how to use relative paths?

**Comment by QiuminGe** [comment]
"args": [
        "--rule-texts=misra.txt"
    ]
Do you know how to use relative paths?

**Comment by ptskyin** [comment]
Great thanks! The misra descriptions show now. 

I'm not sure about relative paths. But, it seems from the Cppcheck manual that the idea is to create a json file with **_"--script"_** and **_"--args"_**, then probably you can use the relative path of the json file in the **_"--addon"_** argument when calling cppcheck.
