### ISSUE TITLE
cpplint settings are ignored

### ISSUE THREAD

**Issue by arrowcircle** [QiuminGe/cpp-check-lint#36]
Hey! When I add configuration for the lint, like `--root=src` or `--filter=-legal/copyright` it just ignores these settings and shows errors anyway.
Is it possible to fix this bug?

**Comment by 0tii** [comment]
@QiuminGe could you elaborate or provide any documentation somewhere for this? I am trying to disable certain warnings like this:

```
"cpp-check-lint.cppcheck.--customargs=": [
        "--filter=[-legal/copyright]"
    ]
```

and it doesn't work.

**Comment by pierow2k** [comment]
@0tii 

I was struggling with this as well. What seems to have worked was the following in `.vscode/settings.json`:

```json
{
    "cpp-check-lint.cppcheck.--suppress=": [
        "legal/copyright",
        "unmatchedSuppression",
        "missingIncludeSystem"
    ],
    "cpp-check-lint.cpplint.--filter=": "-legal/copyright"
}
```

Hope that helps.
