### ISSUE TITLE
variable substitution

### ISSUE THREAD

**Issue by ecorini** [QiuminGe/cpp-check-lint#37]
Is it possible to use variable substitution for configurations?

For example to have a workspace based suppression it would be nice to be able to use a setting like this:
```
"cpp-check-lint.cppcheck.--suppressions-list=": "${worspaceFolder}\\cppcheck-suppression.txt"
```
Thanks!

**Comment by QiuminGe** [comment]
try  v1.5.3   ${workspaceFolder}/cppcheck-suppression.txt
