### ISSUE TITLE
C99 standard not allowed, two C89 standards offered

### ISSUE THREAD

**Issue by lubomilko** [QiuminGe/cpp-check-lint#42]
It is not possible to specify C99 standard and the C89 is duplicated, so the valid choices are: "C89, C89, C11".
![std_c](https://user-images.githubusercontent.com/85431354/160273052-a3805402-4bb6-40e2-9456-e9838037c1b7.jpg)

Also, setting the "c99" option in JSON settings is producing an error:
![c99_json](https://user-images.githubusercontent.com/85431354/160273161-71485b7a-eb7e-4bca-b7d8-924ea3789356.jpg)

Would it be possible to fix it? The plugin is otherwise very helpful! Thank you.

**Comment by QiuminGe** [comment]
Thank you

https://github.com/QiuminGe/cpp-check-lint/pull/43
