### ISSUE TITLE
Using vscode ${workspaceFolder} and other variables in plugin settings

### ISSUE THREAD

**Issue by Dharmesh946** [QiuminGe/cpp-check-lint#48]
Using vscode variables inside settings.json does not seem to work:
>    "cpp-check-lint.cppcheck.-I ": [
        "${workspaceFolder}\\somefolder\\includes"
    ],

cppcheck tells me that it does not find my headers files.

**Comment by Dharmesh946** [comment]
maybe duplicate of #37

**Comment by QiuminGe** [comment]
try 1.5.3
