### ISSUE TITLE
Bump bundled Cppcheck to 2.15

### ISSUE THREAD

**Issue by belliriccardo** [QiuminGe/cpp-check-lint#50]
Hi!
It would be nice to include the latest version of Cppcheck ([version 2.15](https://github.com/danmar/cppcheck/releases/tag/2.15.0)), as the bundled 2.12 version is now one year old. This would be great to include lots of fixes for the addons as well, such as the [many changes received by the misra.py addon.](https://github.com/danmar/cppcheck/commits/main/addons/misra.py?since=2023-09-10&until=2024-09-12)
Not to talk about the other commits to the main Cppcheck program, as they are in the [hundreds.](https://github.com/danmar/cppcheck/commits/2.15.0/?since=2023-09-10&until=2024-09-12) This would greatly improve the experience when using the extension, with minimal effort.
The upgrade should be pretty straightforward if you have already the environment set up. Thanks for the consideration!

**Comment by QiuminGe** [comment]
v1.5.2
