### ISSUE TITLE
--executable": "${workspaceFolder}/cppcheck not supported

### ISSUE THREAD

**Issue by daniel-brosche** [QiuminGe/cpp-check-lint#53]
It seems that `workspaceFolder` substitution is not implemented, this will be helpful if you have cppcheck relative to the workspace.

**Comment by QiuminGe** [comment]
try v1.5.7

**Comment by daniel-brosche** [comment]
Thx, I will try when it's available.

**Comment by QiuminGe** [comment]
it's available.
